# Generated by Django 3.1.3 on 2020-11-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tactic', models.CharField(max_length=100, null=True)),
                ('Technique', models.TextField(max_length=400, null=True)),
                ('TotalTech', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
