# Generated by Django 3.1.3 on 2020-11-25 02:19

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrenv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttp',
            name='Tactic',
        ),
        migrations.AlterField(
            model_name='ttp',
            name='Technique',
            field=django_mysql.models.ListTextField(models.IntegerField(), null=True, size=200),
        ),
    ]
