# Generated by Django 3.1.3 on 2020-11-25 02:26

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrenv', '0002_auto_20201125_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttp',
            name='Tactic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ttp',
            name='Technique',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), null=True, size=200),
        ),
    ]
