# Generated by Django 3.1.3 on 2020-11-25 02:39

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrenv', '0003_auto_20201125_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tacticName', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techniqueName', django_mysql.models.ListTextField(models.CharField(max_length=100), null=True, size=200)),
                ('tactic', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mitrenv.tactic')),
            ],
        ),
    ]
