# Generated by Django 3.1.3 on 2020-11-25 03:00

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrenv', '0004_tactic_techniques'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttp',
            name='FuncTact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='techniques',
            name='techniqueName',
            field=django_mysql.models.ListTextField(models.CharField(max_length=200), null=True, size=200),
        ),
        migrations.AlterField(
            model_name='ttp',
            name='Technique',
            field=django_mysql.models.ListTextField(models.CharField(max_length=200), null=True, size=200),
        ),
    ]
