# Generated by Django 3.1.3 on 2020-11-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrenv', '0005_auto_20201125_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniques',
            name='techniqueRepeat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
