# Generated by Django 3.1.3 on 2020-11-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrenv', '0006_techniques_techniquerepeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniques',
            name='techniqueName',
            field=models.TextField(null=True),
        ),
    ]
