# Generated by Django 3.1.3 on 2020-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrenv', '0007_auto_20201125_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniques',
            name='SubTechnique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techniques',
            name='techniqueId',
            field=models.TextField(null=True),
        ),
    ]
