# Generated by Django 3.1.3 on 2020-11-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrenv', '0009_auto_20201125_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniques',
            name='techniqueRepeat',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
