# Generated by Django 3.1.3 on 2020-11-25 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitrenv', '0010_auto_20201125_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniques',
            name='tactic',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mitrenv.ttp'),
        ),
        migrations.DeleteModel(
            name='Tactic',
        ),
    ]
