# Generated by Django 3.1.3 on 2020-11-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrenv', '0011_auto_20201125_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tacticName', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
