# Generated by Django 3.1.3 on 2020-11-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrenv', '0012_tactic'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniques',
            name='techColor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
