# Generated by Django 3.1.3 on 2020-12-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitrenv', '0014_auto_20201201_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniques',
            name='techColor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
